logging:
  level:
    root: INFO 
    org.springframework.security: TRACE

spring:
    security: 
      oauth2: 
       resourceserver:
          jwt:
            jwk-set-uri: http://auth-server:9000/oauth2/jwks
    datasource: 
        url: jdbc:mysql://localhost/spring-security
        username: root
        password: Thz192900
    jpa:
      open-in-view: 'false'
      hibernate:
        use-new-id-generator-mappings: 'false'
        ddl-auto: update
      show-sql: 'false'

      
