logging:
  level:
    root: INFO 
    org.springframework.security: TRACE

spring:
    security: 
      oauth2: 
       resourceserver:
          jwt:
            jwk-set-uri: http://auth-server:9000/oauth2/jwks
    datasource: 
        url: jdbc:h2:mem:tesdb
        username: sa
        password: 
        driverClassName: org.h2.Driver
    jpa: 
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
      
